<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrganizationalUnitsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Limpiar datos existentes (desactivar foreign keys temporalmente)
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('fa_organizational_units')->truncate();
        DB::table('fa_organizational_unit_types')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Insertar tipos de unidades organizativas
        $tipoGerenciaId = DB::table('fa_organizational_unit_types')->insertGetId([
            'name' => 'Gerencia',
            'staff' => false,
            'is_active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $tipoOficinaId = DB::table('fa_organizational_unit_types')->insertGetId([
            'name' => 'Oficina',
            'staff' => false,
            'is_active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $tipoDepartamentoId = DB::table('fa_organizational_unit_types')->insertGetId([
            'name' => 'Departamento',
            'staff' => false,
            'is_active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $tipoUnidadId = DB::table('fa_organizational_unit_types')->insertGetId([
            'name' => 'Unidad',
            'staff' => false,
            'is_active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Insertar unidades organizativas
        $units = [
            // Gerencias
            [
                'name' => 'Gerencia Administrativa',
                'abbreviation' => 'GER-ADM',
                'code' => 'GER001',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoGerenciaId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gerencia de Comunicaciones e Información',
                'abbreviation' => 'GER-COM',
                'code' => 'GER002',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoGerenciaId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gerencia de Cooperación Externa',
                'abbreviation' => 'GER-COOP',
                'code' => 'GER003',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoGerenciaId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gerencia de Planificación y Gestión Institucional',
                'abbreviation' => 'GER-PLAN',
                'code' => 'GER004',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoGerenciaId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gerencia de Talento Humano',
                'abbreviation' => 'GER-TH',
                'code' => 'GER005',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoGerenciaId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gerencia Financiera',
                'abbreviation' => 'GER-FIN',
                'code' => 'GER006',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoGerenciaId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gerencia Legal',
                'abbreviation' => 'GER-LEG',
                'code' => 'GER007',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoGerenciaId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Oficinas
            [
                'name' => 'Oficina de Información y Respuesta',
                'abbreviation' => 'OIR',
                'code' => 'OFI001',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoOficinaId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oficina principal de la Dirección General',
                'abbreviation' => 'OFI-DG',
                'code' => 'OFI002',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoOficinaId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Departamentos
            [
                'name' => 'Departamento de Registro y Catastro Minero',
                'abbreviation' => 'DEP-RCM',
                'code' => 'DEP001',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoDepartamentoId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Departamento de Regulación',
                'abbreviation' => 'DEP-REG',
                'code' => 'DEP002',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoDepartamentoId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Departamento de Supervisión y Control (GLP)',
                'abbreviation' => 'DEP-SC-GLP',
                'code' => 'DEP003',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoDepartamentoId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Departamento de Supervisión y Control (Minas)',
                'abbreviation' => 'DEP-SC-MIN',
                'code' => 'DEP004',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoDepartamentoId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Departamento de Supervisión y Control (Petróleo)',
                'abbreviation' => 'DEP-SC-PET',
                'code' => 'DEP005',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoDepartamentoId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Unidades
            [
                'name' => 'Archivo Especializado',
                'abbreviation' => 'UNI-ARCH',
                'code' => 'UNI001',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Auditoría Interna',
                'abbreviation' => 'UNI-AUD',
                'code' => 'UNI003',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Call Center',
                'abbreviation' => 'UNI-CC',
                'code' => 'UNI004',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Clínica Institucional',
                'abbreviation' => 'UNI-CLIN',
                'code' => 'UNI005',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dirección Administrativa Financiera',
                'abbreviation' => 'UNI-DAF',
                'code' => 'UNI006',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dirección de Energía',
                'abbreviation' => 'UNI-DE',
                'code' => 'UNI007',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dirección de Hidrocarburos y Minas',
                'abbreviation' => 'UNI-DHM',
                'code' => 'UNI008',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dirección de Hidrocarburos y Minas (En uso por Mirna Argumedo)',
                'abbreviation' => 'UNI-DHM-MA',
                'code' => 'UNI009',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dirección General',
                'abbreviation' => 'UNI-DG',
                'code' => 'UNI010',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dirección Nuclear',
                'abbreviation' => 'UNI-DN',
                'code' => 'UNI011',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'División de Desarrollo Sostenible y Equidad Energética',
                'abbreviation' => 'UNI-DDSEE',
                'code' => 'UNI012',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'División de Eficiencia y Equidad Energética',
                'abbreviation' => 'UNI-DEEE',
                'code' => 'UNI013',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'División de Gestión de Eficiencia Energética',
                'abbreviation' => 'UNI-DGEE',
                'code' => 'UNI014',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'División de Mercados Energéticos',
                'abbreviation' => 'UNI-DME',
                'code' => 'UNI015',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'División de Planificación y Estadísticas Energéticas',
                'abbreviation' => 'UNI-DPEE',
                'code' => 'UNI016',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'División Técnica Administrativa Minera',
                'abbreviation' => 'UNI-DTAM',
                'code' => 'UNI017',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'División Técnica Administrativa Petrolera',
                'abbreviation' => 'UNI-DTAP',
                'code' => 'UNI018',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'OIPEN',
                'abbreviation' => 'UNI-OIPEN',
                'code' => 'UNI019',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oficial de Cumplimiento',
                'abbreviation' => 'UNI-OC',
                'code' => 'UNI020',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Petróleo, Minas, Regulación y Call Center',
                'abbreviation' => 'UNI-PMRC',
                'code' => 'UNI021',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PNUD',
                'abbreviation' => 'UNI-PNUD',
                'code' => 'UNI022',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sala de reuniones de la Dirección General',
                'abbreviation' => 'UNI-SRDG',
                'code' => 'UNI023',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Servicios Generales',
                'abbreviation' => 'UNI-SG',
                'code' => 'UNI024',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Talento Humano',
                'abbreviation' => 'UNI-TH',
                'code' => 'UNI025',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'UGDA',
                'abbreviation' => 'UNI-UGDA',
                'code' => 'UNI027',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unidad de Compras Públicas',
                'abbreviation' => 'UNI-COMP',
                'code' => 'UNI028',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unidad de Contabilidad',
                'abbreviation' => 'UNI-CONT',
                'code' => 'UNI030',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unidad de Género',
                'abbreviation' => 'UNI-GEN',
                'code' => 'UNI031',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unidad de Gestión Documental',
                'abbreviation' => 'UNI-GDOC',
                'code' => 'UNI032',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unidad de Gestión Documental y Archivo',
                'abbreviation' => 'UNI-GDOCA',
                'code' => 'UNI033',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unidad de Presupuesto',
                'abbreviation' => 'UNI-PRES',
                'code' => 'UNI034',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unidad de Seguridad y Salud Ocupacional',
                'abbreviation' => 'UNI-SSO',
                'code' => 'UNI035',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unidad de Seguridad y Saludo Ocupacional',
                'abbreviation' => 'UNI-SSO2',
                'code' => 'UNI036',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unidad de Sistemas de Gestión',
                'abbreviation' => 'UNI-SGEST',
                'code' => 'UNI037',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unidad de Tecnología de la Información',
                'abbreviation' => 'UNI-TI',
                'code' => 'UNI026',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unidad de Tesorería',
                'abbreviation' => 'UNI-TES',
                'code' => 'UNI041',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unidad de Transporte',
                'abbreviation' => 'UNI-TRANS',
                'code' => 'UNI042',
                'is_active' => true,
                'fa_organizational_unit_type_id' => $tipoUnidadId,
                'fa_organizational_unit_id' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('fa_organizational_units')->insert($units);
    }
}
